[package]
name = "wave_function_collapse"
version = "0.1.0"
edition = "2024"

[dependencies]
bittyset = "0.1.1"
sdl2 = { version = "0.37.0", features = ["ttf"] }
softbuffer = "0.4.6"
winit = "0.30.8"
